# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
 pipelines:
   - pipeline: Result-app
     source: Result-app
     trigger: true

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b1d0523c-41af-4566-a513-b8b9608899c6'
  imageRepository: 'cicdpipeline'
  containerRegistry: 'myvotingrepo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
 name: 'Agent-1'

stages:
- stage: DeploytoQA
  displayName: DeploytoQA
  jobs:
  - job: DeploytoQA
    displayName: DeploytoQA
    pool:
     name: 'Agent-1'
    steps: 
     - task: Bash@3
       inputs:
        targetType: 'inline'
        script: 'scp /home/azureuser/myagent/_work/3/s/docker-compose.yml azureuser@40.119.43.230:/home/azureuser/'
